
type Employee {
    id: Int
    name: String
    email: String
    phone: String
    profile: Profile
}

input FilterInput{
    id: Int
    email: String
}

input EmployeeInput {
    name: String
    email: String
    phone: String
}

type Query {
    employee: Employee
    employees: [Employee]
}

type Mutation {
    createEmployee(data: EmployeeInput): Employee!
    updateEmployee(id: Int!, data: EmployeeInput): Employee!
    deleteEmployee(id: Int!):Boolean
    deleteEmployeeByEmail(filtro: FilterInput!):Boolean
}