
type Employee {
    id: Int
    name: String
    email: String
    phone: String
    profile: Profile
}

type Query {
    employee: Employee
    employees: [Employee]
}

type Mutation {
    createEmployee(name: String, email: String, phone: String): Employee!
}